# Generated by Django 5.0.6 on 2026-07-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('include_technical_appendix', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_reports', to='scanner.scanproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
