# Generated by Django 5.0.6 on 2026-07-18 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('file', 'Single File Upload'), ('zip', 'Project Archive (.zip)'), ('paste', 'Pasted Code Snippet'), ('github', 'GitHub Repository')], max_length=10)),
                ('source_reference', models.CharField(blank=True, help_text="Original filename, repo URL, or 'pasted snippet'", max_length=500)),
                ('scan_path', models.CharField(blank=True, help_text='Absolute path on disk to the scanned code root', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('run_bandit', models.BooleanField(default=True)),
                ('run_semgrep', models.BooleanField(default=True)),
                ('run_ast_checks', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('files_scanned', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bandit', 'Bandit'), ('semgrep', 'Semgrep'), ('ast', 'ARGUS AST Engine')], max_length=10)),
                ('rule_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='medium', max_length=10)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('file_path', models.CharField(max_length=1000)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('end_line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True)),
                ('cwe_id', models.CharField(blank=True, max_length=50)),
                ('owasp_category', models.CharField(blank=True, max_length=100)),
                ('remediation', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scanproject')),
            ],
            options={
                'ordering': ['severity', 'file_path', 'line_number'],
                'indexes': [models.Index(fields=['project', 'severity'], name='scanner_fin_project_d9a4e6_idx'), models.Index(fields=['project', 'source'], name='scanner_fin_project_0583d4_idx')],
            },
        ),
    ]
