# Generated by Django 5.0.6 on 2026-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanproject',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=10),
        ),
    ]
